// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpatzcirlmtctefylnnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYXR6Y2lybG10Y3RlZnlsbm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDgwMTEsImV4cCI6MjA2NzEyNDAxMX0.NepHCU82RyFVCtM1p3zch0eqANBu_umwIPHQQBbBsc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});